### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by ariley** [nigel-daniels/MMM-3Day-Forecast#27]
This is what I get when trying to launch MagicMirror after installing your module:

[13.12.2021 04:38.38.095] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-3Day-Forecast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-3Day-Forecast/node_helper.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-3Day-Forecast/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[13.12.2021 04:38.38.097] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[13.12.2021 04:38.38.098] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[13.12.2021 04:38.38.318] [LOG]   Launching application.
^C/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT

**Comment by nigel-daniels** [comment]
Hi, did you do an `npm install` in the module directory?  If you did were there any errors during that?  If there were it may be worth following up on those.

**Comment by ariley** [comment]
Thank you, but I switched to a different module and that works. :-)


Agnes Riley
9176607221
***@***.***
[image: twitter] <https://twitter.com/agir>
[image: instagram] <https://instagram.com/agiriley>

**Comment by nigel-daniels** [comment]
np, if you get the change could you run the `npm install` and look for any error output? It would be useful to know if there is a problem that needs addressing.

**Comment by nigel-daniels** [comment]
@migasQ Thanks for your help with this, it's much appreciated.
